server:
  port:
    8088

spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: ??? ???
    password: ??? ??
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            enalbe: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hamadb
    username:
    password:


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 620643424996-qpm2d4efe6c1079fi67a3th9bpg1tu8f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8088/login/oauth2/code/google
            token-uri: https://oauth2.googleapis.com/token
            resource-uri: https:www.googleapis.com/oauth2/v2/userinfo
            scope:
              - email
              - profile

          kakao:
            client-id : f26e0636a3b7f31a8acf97ee86964823
            client-name : Kakao
            client-authentication-method: POST
            redirect-uri: http://localhost:8088/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

          naver:
            client-id: _g0675caBA3GAyitkkK7
            client-secret: ZmAsB5FUnn
            scope:
              - name
              - email
            client-name: Naver # ????? ??? ?? ????? ???? ?????.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/login/oauth2/code/naver

        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # ????? json? response ???? ????.


logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: vpJyPJsLwlWRKY52bp/1cB/uHeGiVMXGhP8XEuT2640= # ??? ???? Base64? ???? ?
  refresh-token-validity-in-seconds: 1209600 # 14?
  access-token-validity-in-seconds: 43200 # 12??

fcm:
  key:
    path: firebase-admin.json
    scope: https://www.googleapis.com/auth/cloud-platform
